### ISSUE TITLE
[Bug] Killed by zombie check won't trigger

### ISSUE THREAD

**Issue by AgentWesker** [hallucinogenic/-ZR-Zombie-Rank#1]
Lines 95 to 99 in zr_rank/events.sp have a check for human being killed by zombie, but it is nested within a check that the attacker is Human and victim is Zombie, so it won't get triggered.

**Comment by luis-rei97** [comment]
Fixed in the next update ;)

**Comment by AgentWesker** [comment]
Another bug, line 100 should be team == 3 (counter terrorist)
