### ISSUE TITLE
[Request] Receive points for winning the round

### ISSUE THREAD

**Issue by AgentWesker** [hallucinogenic/-ZR-Zombie-Rank#2]
Currently no points assigned in the event of Humans / Zombies winning the round, can this be a cvar?

**Comment by luis-rei97** [comment]
Currently, I'm testing in which best possible way you can get points by winning the rounds.
For ZM, its very eazy (just trigger the winner of the round), but for ZE it can be a little bit difficult (I'm currently testing the "nukes" made by the map, so it only gives points if you finish a map).

**Comment by AgentWesker** [comment]
Ah, maybe something like when someone dies add to a counter (that resets after 10? seconds) and if the round ends before that timer goes up -> sees 10+ ppl died = nuke went off ?

**Comment by AgentWesker** [comment]
Included this with my latest pull request
https://github.com/hallucinogenic/-ZR-Zombie-Rank/pull/8

**Comment by luis-rei97** [comment]
Included in Version 1.5 of the Plugin.
