### ISSUE TITLE
[Request] Add notification if ranks are disabled

### ISSUE THREAD

**Issue by AgentWesker** [hallucinogenic/-ZR-Zombie-Rank#4]
On infect / death add a notice in chat if ranks were disabled due to minimum player count

**Comment by AgentWesker** [comment]
Fixed in https://github.com/hallucinogenic/-ZR-Zombie-Rank/pull/8

**Comment by luis-rei97** [comment]
I'll add this, but with an option for the server manager (or owner) to disable the notifications (it can be a lot of stuff in the screen, so people may don't want it.
